
import { Habit } from './types';

export const INITIAL_HABITS: Habit[] = [
  {
    id: '1',
    name: 'Drink Water',
    type: 'build',
    icon: 'water_drop',
    color: '#93c5fd',
    streak: 5,
    completedToday: false,
    private: false,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    reminderTime: '08:00'
  },
  {
    id: '2',
    name: 'No Sugar',
    type: 'break',
    icon: 'block',
    color: '#fdba74',
    streak: 12,
    completedToday: true,
    private: true,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  },
  {
    id: '3',
    name: 'Meditate',
    type: 'build',
    icon: 'self_improvement',
    color: '#30e8ab',
    streak: 20,
    completedToday: true,
    private: false,
    frequency: ['M', 'W', 'F'],
  },
  {
    id: '4',
    name: 'Limit Social',
    type: 'break',
    icon: 'do_not_disturb_on',
    color: '#fdba74',
    streak: 2,
    completedToday: false,
    private: true,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  },
  {
    id: '5',
    name: 'Read 20 Pages',
    type: 'build',
    icon: 'menu_book',
    color: '#c084fc',
    streak: 8,
    completedToday: false,
    private: false,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  },
  {
    id: '6',
    name: 'Morning Yoga',
    type: 'build',
    icon: 'spa',
    color: '#4ade80',
    streak: 15,
    completedToday: true,
    private: false,
    frequency: ['M', 'W', 'F'],
  },
  {
    id: '7',
    name: 'No Junk Food',
    type: 'break',
    icon: 'fastfood',
    color: '#f87171',
    streak: 4,
    completedToday: false,
    private: false,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  },
  {
    id: '8',
    name: 'Caffeine Free',
    type: 'break',
    icon: 'coffee',
    color: '#fbbf24',
    streak: 1,
    completedToday: true,
    private: false,
    frequency: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  }
];

export const CATEGORIES = {
  health: ['water_drop', 'fitness_center', 'directions_run', 'spa', 'fastfood', 'coffee'],
  mindfulness: ['self_improvement', 'psychology', 'bedtime', 'history_edu'],
  productivity: ['menu_book', 'edit_note', 'check_circle', 'schedule'],
};
